### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/igb-geonode#7] opened 2019-05-16 19:49 UTC
implement user management via IGB LDAP, if possible also including groups (departments, research groups);

Check the requirements document for more information, [here](https://docs.google.com/document/d/1YtPCgrtOJddnOSqiNrhFb-I0R2p0AaUTG3iJJaciwNs/edit);

**Comment by simboss** [comment] 2019-05-17 12:42
@ricardogsilva talk to @giohappy as he would want to port over to geonode the work done on LDAP for NFD.

The idea is to release this feature to the core GeoNode asap.

**Comment by ricardogsilva** [comment] 2019-05-17 14:12
OK

**Comment by giohappy** [comment] 2019-05-21 13:35
@simboss core GeoNode, are you sure? I would consider it a contrib (external app), to be kept in its own repo as we're doing for the other contrib modules (monitoring, etc.)

**Comment by simboss** [comment] 2019-05-21 13:37
that works for me.

As far as I am concerned a contrib app that lives under the geonode organization with its own repo falls within my concept of "core".

I just don't want to have this work go under a specific customization. Got it.

**Comment by giohappy** [comment] 2019-05-21 13:47
@ricardogsilva the idea is to use django-ldap (as you confirmed) and write a thin adapter layer on top of it to match geonode's users and groups model

**Comment by ricardogsilva** [comment] 2019-05-24 16:16
I've done a local install of an OpenLDAP server and managed to also setup [Apache Directory Studio](https://directory.apache.org/studio/) for managing it - a nice tool btw

I was able to get basic LDAP logins working by just setting the correct configuration variables in the `settings.py` file.

Next step is to tweak the config in order to extract attributes and group information from LDAP - Apparently [django-auth-ldap](https://django-auth-ldap.readthedocs.io/en/latest/) is so flexible that it may not even warrant creating any geonode-specific layer on top of it.

**Comment by ricardogsilva** [comment] 2019-06-10 11:03
After more thorough testing I realized that some modification to geonode's source code would be needed in order to correctly map LDAP groups to geonode groups (and ensure permissions are enforced). PR:

geosolutions-it/geonode#322 

I'm awaiting some guidance on how to best include this code upstream, as my original approach of supplying a `geonode.contrib` app seems to not be viable.

**Comment by afabiani** [comment] 2019-06-10 13:38
@ricardogsilva you should add the app here

https://github.com/GeoNode/contribs

along with a well formatted readme explaining the steps on how the install, configure and use the plugin

(see as an instance https://github.com/GeoNode/contribs/tree/master/geonode/contrib/worldmap)

**Comment by ricardogsilva** [comment] 2019-06-10 16:40
@afabiani 
How would I install the package with this new `contribs` approach?

My pending PR features a custom authentication backend that needs to be available on the python path when geonode is running. So it either needs to be installed in the python (virtual)env or it must be part of the geonode project (if using one).

The standard approach would be to add a `setup.py` file and instruct the user to `git clone <repo> && pip install <repo_name>` in order to install it. However, in this case it feels a little wonky, as I'd add a `setup.py` inside my `ldap` subdir of the contribs repo. It is certainly doable though.

Would you approve of this? Or do you have something else in mind?

I've looked into the READMEs of the other contrib packages and it seems this is still a WIP for them too. 

For example, the [worldmap instructions](https://github.com/GeoNode/contribs/tree/master/geonode/contrib/worldmap#geonodeworldmap-without-a-geonode-project) mention doing a `pip install -e .` but the source code in `contribs/geonode/contrib/worldmap` does not contain a `setup.py` file, so I guess they haven't been fully updated since extracting it from main geonode repo.

**Comment by ricardogsilva** [comment] 2019-06-12 14:39
@afabiani 

GeoNode/geonode-contribs#2

**Comment by afabiani** [comment] 2019-06-14 09:13
@ricardogsilva that seems to be merged on `geonode-contribs`

I'm closing this. Let's move the discussion on the contribs repo.

**Closed by afabiani** 2019-06-14 09:13 UTC
